apiVersion: v1
kind: ConfigMap
metadata:
  name: linker-config
  namespace: linker
data:
  PORT: "3001"
  NEXTAUTH_URL: "https://media-fidigitals.space"
  INTERNAL_API_URL: "http://backend:3001/api"
  NEXT_PUBLIC_API_URL: "https://media-fidigitals.space/api"
